export enum ComponentTypes {
    AllCallForwardingComponent = 1,
    CallForwardingBusyComponent = 2,
    SelectiveCallAcceptanceComponent = 3,
    SelectiveCallRejectionComponent = 4,
    FindMeFollowMeComponent = 5,
    SpeedDialingComponent = 6,
    UnavailableCallForwardingComponent = 7,
    VoicemailComponent = 8,
    CallRecordsComponent = 9,
    AnonymousCallRejectionComponent = 10,
    DataUsageComponent = 11,
    SimRingComponent = 12,
    HuntingComponent = 13,
    AutoAttendantComponent = 14,
    BillingManagementComponent = 15,
    DoNotDisturbComponent = 16,
    InternationalminutesComponent = 17,
    CallForwardingNoAnswerComponent = 18,
    ComplexComponent = 19
}
