export enum FeatureTypes {
    'All Call Forwarding' = 1,
    'Call Forwarding - Busy' = 2,
    'Selective Call Acceptance' = 3,
    'Selective Call Rejection' = 4,
    'Find-Me Follow-Me' = 5,
    'Speed Dialing' = 6,
    'Unavailable Call Forwarding' = 7,
    'Voicemail' = 8,
    'CDRs' = 9,
    'Anonymous Call Rejection' = 10,
    'Data Usage' = 11,
    'Sim Ring' = 12,
    'Hunting' = 13,
    'Auto Attendant' = 14,
    'Billing Management' = 15,
    'Do Not Disturb' = 16,
    'International' = 17,
    'Call Forwarding - No Answer' = 18,
    'Complex' = 19
}
